# Generated by Django 5.1.6 on 2025-03-01 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fio', models.TextField(verbose_name='ФИО врача')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('specialty', models.TextField(verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fio', models.TextField(verbose_name='ФИО пациента')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('patient_age', models.IntegerField(verbose_name='Возраст')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('prescriptions', models.JSONField(verbose_name='Рецепты')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер кабинета')),
                ('room_name', models.TextField(verbose_name='Название кабинета')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('prescriptions', models.JSONField(help_text='Пример: {"drug1": "paracetamol", "drug2": "validol"}', verbose_name='Рецепты')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient', verbose_name='Пациент')),
                ('room', models.ForeignKey(db_column='room_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.room', verbose_name='Кабинет')),
            ],
        ),
    ]
