# Generated by Django 5.1.6 on 2025-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescriptions',
            field=models.JSONField(blank=True, null=True, verbose_name='Рецепты'),
        ),
    ]
