# Generated by Django 5.1.4 on 2025-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("hypertension", models.IntegerField()),
                ("heart_disease", models.IntegerField()),
                ("ever_married", models.BooleanField()),
                ("work_type", models.CharField(max_length=50)),
                ("residence_type", models.CharField(max_length=50)),
                ("avg_glucose_level", models.FloatField()),
                ("bmi", models.FloatField()),
                ("smoking_status", models.CharField(max_length=20)),
                ("stroke_prediction", models.FloatField()),
            ],
        ),
    ]
