# Generated by Django 5.2.1 on 2025-05-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
